# Generated by Django 5.1.15 on 2026-04-09 14:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('picking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('required_role', models.CharField(choices=[('manager', 'Manager'), ('safety', 'Safety Officer'), ('admin', 'Admin')], help_text='Which role must approve this step.', max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('actioned_at', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_actions', to=settings.AUTH_USER_MODEL)),
                ('picking_slip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='picking.pickingslip')),
            ],
            options={
                'db_table': 'approvals',
                'ordering': ['created_at'],
            },
        ),
    ]
