# Generated by Django 5.1.15 on 2026-04-09 14:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('organization', '0001_initial'),
        ('ppe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PickingSlip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_type', models.CharField(choices=[('expiry', 'PPE Expired'), ('lost', 'PPE Lost'), ('damaged', 'PPE Damaged'), ('new', 'New Employee / First Issue')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved — Ready to Issue'), ('issued', 'Issued'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('qr_code', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_slips', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='picking_slips', to='organization.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='picking_slips', to='organization.employee')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_slips', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_slips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'picking_slips',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PickingSlipItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('picking_slip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='picking.pickingslip')),
                ('ppe_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slip_items', to='ppe.ppeitem')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.warehouse')),
            ],
            options={
                'db_table': 'picking_slip_items',
            },
        ),
        migrations.CreateModel(
            name='ScanLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_data', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('mismatch', 'Mismatch'), ('expired', 'Expired Slip')], default='valid', max_length=20)),
                ('scan_time', models.DateTimeField(auto_now_add=True)),
                ('picking_slip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to='picking.pickingslip')),
                ('ppe_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_logs', to='ppe.ppeitem')),
                ('scanned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'scan_logs',
                'ordering': ['-scan_time'],
            },
        ),
        migrations.AddIndex(
            model_name='pickingslip',
            index=models.Index(fields=['status'], name='picking_sli_status_3319e4_idx'),
        ),
        migrations.AddIndex(
            model_name='pickingslip',
            index=models.Index(fields=['employee'], name='picking_sli_employe_65ad85_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pickingslipitem',
            unique_together={('picking_slip', 'ppe_item')},
        ),
    ]
