# Generated by Django 5.1.15 on 2026-04-09 14:18

import core.utils.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('ppe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('location_description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='organization.site')),
            ],
            options={
                'db_table': 'warehouses',
                'unique_together': {('site', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('change_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out')], max_length=5)),
                ('quantity', models.PositiveIntegerField(validators=[core.utils.validators.validate_positive])),
                ('reference_type', models.CharField(choices=[('ISSUE', 'PPE Issue'), ('RETURN', 'PPE Return'), ('ADJUSTMENT', 'Manual Adjustment'), ('INITIAL', 'Initial Stock')], max_length=20)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('ppe_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='ppe.ppeitem')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'stock_movements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_available', models.PositiveIntegerField(default=0, validators=[core.utils.validators.validate_positive])),
                ('reorder_level', models.PositiveIntegerField(default=10, help_text='Alert is triggered when quantity_available drops to or below this value.')),
                ('ppe_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='ppe.ppeitem')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'stock_items',
                'indexes': [models.Index(fields=['warehouse'], name='stock_items_warehou_5d5782_idx')],
                'unique_together': {('ppe_item', 'warehouse')},
            },
        ),
    ]
