# Generated by Django 5.1.15 on 2026-04-09 14:18

import core.utils.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PPEItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(choices=[('head', 'Head Protection'), ('eye', 'Eye & Face Protection'), ('respiratory', 'Respiratory Protection'), ('hand', 'Hand Protection'), ('foot', 'Foot Protection'), ('hearing', 'Hearing Protection'), ('hi_vis', 'High-Visibility Clothing'), ('body', 'Body / Fall Protection'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_critical', models.BooleanField(default=False, help_text='Critical PPE requires additional oversight when expired.')),
                ('default_validity_days', models.PositiveIntegerField(help_text='System-wide default validity in days if no config override exists.', validators=[core.utils.validators.validate_positive_nonzero])),
                ('requires_serial_tracking', models.BooleanField(default=False, help_text='True for items like helmets that need individual serial numbers.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ppe_items',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PPEConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope_type', models.CharField(choices=[('system', 'System-wide'), ('site', 'Site'), ('department', 'Department')], max_length=20)),
                ('scope_id', models.UUIDField(blank=True, null=True)),
                ('validity_days', models.PositiveIntegerField(validators=[core.utils.validators.validate_positive_nonzero])),
                ('grace_days', models.PositiveIntegerField(default=7, help_text="Number of days before expiry to mark status as 'expiring_soon'.")),
                ('requires_approval', models.BooleanField(default=True)),
                ('approval_levels', models.JSONField(default=list, help_text='Ordered list of approval steps. Example: [{"role": "manager", "required": true}]')),
                ('ppe_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='ppe.ppeitem')),
            ],
            options={
                'db_table': 'ppe_configurations',
                'indexes': [models.Index(fields=['ppe_item', 'scope_type'], name='ppe_configu_ppe_ite_ea7a69_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmployeePPE',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('expiring_soon', 'Expiring Soon'), ('expired', 'Expired'), ('blocked', 'Blocked'), ('pending_issue', 'Pending Issue')], db_index=True, default='pending_issue', max_length=20)),
                ('last_inspection_date', models.DateField(blank=True, null=True)),
                ('condition_status', models.CharField(blank=True, max_length=50)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ppe_assignments', to='organization.employee')),
                ('ppe_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ppe.ppeitem')),
            ],
            options={
                'db_table': 'employee_ppe',
                'indexes': [models.Index(fields=['employee'], name='employee_pp_employe_2f8851_idx'), models.Index(fields=['expiry_date'], name='employee_pp_expiry__957b7b_idx'), models.Index(fields=['status'], name='employee_pp_status_3cf0fa_idx')],
                'unique_together': {('employee', 'ppe_item')},
            },
        ),
        migrations.CreateModel(
            name='DepartmentPPERequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_required', models.BooleanField(default=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ppe_requirements', to='organization.department')),
                ('ppe_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppe.ppeitem')),
            ],
            options={
                'db_table': 'department_ppe_requirements',
                'unique_together': {('department', 'ppe_item')},
            },
        ),
    ]
